repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.63.2
    hooks:
      - id: swiftlint
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.59.1
    hooks:
      - id: swiftformat
